"""
Plastic SSCx related utility functions (most of them deal with the custom directory and file structure)
author: András Ecker, last update: 11.2021
"""

import os
import warnings
import pickle
import numpy as np
import pandas as pd


SIMS_DIR = "/gpfs/bbp.cscs.ch/project/proj96/scratch/home/ecker/simulations"


def ensure_dir(dir_path):
    if not os.path.exists(dir_path):
        os.makedirs(dir_path)


def load_sim_path(project_name):
    """Loads in simulation paths as pandas MultiIndex DataFrame generated by bbp-workflow"""
    pklf_name = os.path.join(SIMS_DIR, project_name, "analyses", "simulations.pkl")
    return pd.read_pickle(pklf_name)


def _idx2str(idx, level_name):
    """Helper function to convert pandas.Index to string"""
    value = ("%.2f" % idx).replace('.', 'p') if isinstance(idx, float) else "%s" % idx
    return "%s%s" % (level_name, value)


def midx2str(midx, level_names):
    """Helper function to convert pandas.MultiIndex to string"""
    if len(level_names) == 1:  # it's not actually a MultiIndex
        return _idx2str(midx, level_names[0]) + "_"
    elif len(level_names) > 1:
        str_ = ""
        for i, level_name in enumerate(level_names):
            str_ += _idx2str(midx[i], level_name) + "_"
        return str_
    else:
        raise RuntimeError("Incorrect level_names passed")


def get_spikes(sim, t_start, t_end):
    """Extracts spikes with bluepy"""
    spikes = sim.spikes.get(t_start=t_start, t_end=t_end)
    return spikes.index.to_numpy(), spikes.values


def calc_rate(spike_times, N, t_start, t_end, bin_size=10):
    """Calculates populational firing rate"""
    t_bins = np.arange(t_start, t_end+bin_size, bin_size)
    rate, _ = np.histogram(spike_times, t_bins)
    return rate / (N*1e-3*bin_size)  # *1e-3 ms to s conversion


def get_tc_spikes(sim, t_start, t_end):
    """Extracts spikes from BC stimulus block 'spikeReplay'"""
    spikef_name = sim.config.Stimulus_spikeReplay.SpikeFile  # TODO: add some error handling...
    f_name = spikef_name if os.path.isabs(spikef_name) else os.path.join(sim.config.Run_Default.CurrentDir, spikef_name)
    tmp = np.loadtxt(f_name, skiprows=1)
    spike_times, spiking_gids = tmp[:, 0], tmp[:, 1].astype(int)
    idx = np.where((t_start < spike_times) & (spike_times < t_end))[0]
    return spike_times[idx], spiking_gids[idx]


def load_tc_gids(project_name):
    """Loads in VPM and POM gids from saved files"""
    vpm_gids, pom_gids = None, None
    proj_dir = os.path.join(project_name, "projections")
    if os.path.isdir(proj_dir):
        for f_name in os.listdir(proj_dir):
            if f_name[-4:] == ".txt" and "VPM" in f_name:
                vpm_gids = np.loadtxt(os.path.join(proj_dir, f_name))[:, 0].astype(int)
            if f_name[-4:] == ".txt" and "POM" in f_name:
                pom_gids = np.loadtxt(os.path.join(proj_dir, f_name))[:, 0].astype(int)
    return vpm_gids, pom_gids


def load_patterns(project_name, seed=None):
    """Loads in patterns from saved files (pretty custom structure and has a bunch of hard coded parts)"""
    pklf_name = None
    seed_str = "seed%i" % seed if seed is not None else "seed"
    for f_name in os.listdir(os.path.join(SIMS_DIR, project_name, "input_spikes")):
        if f_name[-4:] == ".pkl" and seed_str in f_name and "pattern_gids" in f_name:
            pklf_name = f_name
            with open(os.path.join(SIMS_DIR, project_name, "input_spikes", pklf_name), "rb") as f:
                pattern_gids = pickle.load(f)
    if pklf_name:
        metadata = pklf_name.split('__')[:-1]
        for f_name in os.listdir(os.path.join(SIMS_DIR, project_name, "projections")):
            if pklf_name.split("__nc")[0] + ".txt" == f_name:
                tmp = np.loadtxt(os.path.join(SIMS_DIR, project_name, "projections", f_name))
                gids, pos = tmp[:, 0].astype(int), tmp[:, 1:]
                return pattern_gids, gids, pos, metadata
            else:
                warnings.warn("Couldn't find saved positions in %s/projections" % project_name)
                return pattern_gids, None, None, metadata
    else:
        raise RuntimeError("Couldn't find saved *pattern_gids*.pkl in %s/input_spikes" % project_name)





