analysis:
  spikes:
    extraction:
      limit: null
      neuron_classes:
        ALL:
          query:
            synapse_class:
            - EXC
            - INH
        ALL_EXC:
          query:
            synapse_class:
            - EXC
        ALL_INH:
          query:
            synapse_class:
            - INH
        L1_INH:
          query:
            layer:
            - 1
            synapse_class:
            - INH
        L23_EXC:
          query:
            layer:
            - 2
            - 3
            synapse_class:
            - EXC
        L23_INH:
          query:
            layer:
            - 2
            - 3
            synapse_class:
            - INH
        L4_EXC:
          query:
            layer:
            - 4
            synapse_class:
            - EXC
        L4_INH:
          query:
            layer:
            - 4
            synapse_class:
            - INH
        L5_EXC:
          query:
            layer:
            - 5
            synapse_class:
            - EXC
        L5_INH:
          query:
            layer:
            - 5
            synapse_class:
            - INH
        L6_EXC:
          query:
            layer:
            - 6
            synapse_class:
            - EXC
        L6_INH:
          query:
            layer:
            - 6
            synapse_class:
            - INH
      node_set: null
      population: S1nonbarrel_neurons
      report:
        type: spikes
      windows:
        w_evoked:
          bounds:
          - 0
          - 500
          initial_offset: 2000
          n_trials: 10
          trial_steps_value: 1000
          window_type: evoked
        w_spont:
          bounds:
          - -500
          - 0
          initial_offset: 2000
          n_trials: 10
          trial_steps_value: 1000
          window_type: spontaneous
    features:
    - function: blueetl.external.bnac.calculate_features.calculate_features_multi
      groupby:
      - simulation_id
      - circuit_id
      - neuron_class
      - window
      params:
        export_all_neurons: true
      type: multi
cache:
  path: /gpfs/bbp.cscs.ch/project/proj83/home/pokorny/SimplifiedConnectomeModels/analyses_v2_recal/SSCx-HexO1-Release-TC-R2__ConnRewireOrder1Hex0EE__Hex0-Evoked-PFR-VPM-Scan
simulation_campaign: /gpfs/bbp.cscs.ch/data/scratch/proj83/home/pokorny/SimplifiedConnectomeModels/simulations_v2_recal/SSCx-HexO1-Release-TC-R2__ConnRewireOrder1Hex0EE__Hex0-Evoked-PFR-VPM-Scan/config.json
version: 4
